### ISSUE TITLE
Current temperature reading not displaying

### ISSUE THREAD

**Issue by richmitch** [cbrandlehner/homebridge-daikin-tempsensor-nocloud#48]
Hi.  I hope you can help me.  

When I check the sensor info:

`http://192.168.nn.nn/skyfi/aircon/get_sensor_info`

it responds with:

`ret=OK,err=0,htemp=17,otemp=-`

but no temperature is shown in the accessory:

![image](https://user-images.githubusercontent.com/17056626/139508797-bf95223d-c2f5-4905-a343-17164f9c37b0.png)

I'm also getting this warning in the status page:

`This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.`

Any ideas how to fix this?

**Comment by richmitch** [comment]
After checking the debug log I can see the details below.  Its getting the response back ok but its not updating the accessory temperature.

`[10/30/2021, 10:03:42 AM] [Upstairs Temperature] getCurrentOutsideTemperature using http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] attempting request: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] queuing (append) request: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] executing queued request: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] requesting from cache: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] cache MISS: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] requesting from API: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] set cache: path: http://192.168.20.83/skyfi/aircon/get_sensor_info
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] responding from API: ret=OK,err=0,htemp=19,otemp=-
[10/30/2021, 10:03:42 AM] [Upstairs Temperature] queued request finished: path: http://192.168.20.83/skyfi/aircon/get_sensor_info`

**Comment by richmitch** [comment]
And finally, this error may help 

`[10/30/2021, 10:18:15 AM] [homebridge-daikin-tempsensor-nocloud] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1569:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-daikin-tempsensor-nocloud/index.js:250:25
    at /usr/local/lib/node_modules/homebridge-daikin-tempsensor-nocloud/index.js:163:11
    at fn (/usr/local/lib/node_modules/homebridge-daikin-tempsensor-nocloud/index.js:199:7)
    at Request.callback (/usr/local/lib/node_modules/homebridge-daikin-tempsensor-nocloud/node_modules/superagent/src/node/index.js:890:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-daikin-tempsensor-nocloud/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:402:35)`

**Comment by cbrandlehner** [comment]
It looks like the connection to the AC is not working.
If you use this URL in your browser, what is the result?

`http://192.168.20.83/skyfi/aircon/get_sensor_info `

**Comment by richmitch** [comment]
I can connect ok and get info back.

`ret=OK,err=0,htemp=21,otemp=-`

**Comment by cbrandlehner** [comment]
I see. Mine reports:
`ret=OK,htemp=21.0,hhum=-,otemp=5.0,err=0,cmpfreq=0`
As you can see your AC does not report a value for the outside temperature. Mine does not report a value for humidity.

@richmitch am I right that also your DAIKIN APP does not show a value for the outside temperature?

**Comment by richmitch** [comment]
Hi.  Yes, I don't have an outside temp sensor or the humidity that you appear to have.  Does the Characteristic require a response for all values or a minimum response?  The otemp conversion is going to throw a NaN but I would have though that the htemp would still get set and displayed.  I haven't set up the project in vscode to debug it yet because I wasn't clear how to attach the process to the vscode debug session.  I can see its described in various pages so may be able to give it a go at the weekend if you don't get to it.  Thanks for writing this btw.

**Comment by richmitch** [comment]
One thing I noticed is that you appear to be setting CurrentTemperature to the outside temperature value and not the house temperature value.  That looks to be deliberate, are you basing this on the outside temp rather than the house temp?

```this.temperatureService
      .getCharacteristic(Characteristic.CurrentTemperature)
      .setProps({minValue: Number.parseFloat('-50'),
                 maxValue: Number.parseFloat('100')})
      .on('get', this.getCurrentOutsideTemperature.bind(this));```

**Comment by HelderCardoso** [comment]
Hi.

When I check the sensor info:

http://192.168.nn.nn/aircon/get_sensor_info

it responds with:

ret=OK,htemp=27.5,hhum=-,otemp=14.0,err=0,cmpfreq=0

but no temperature is shown in the accessory:

I'm also getting this warning in the status page:

Any ideas how to fix this?

**Comment by cbrandlehner** [comment]
@richmitch Yes, I am reading outside temperature.
Today I released a new version which allows to switch between inside and outside temperature.

**Comment by cbrandlehner** [comment]
Can you please all retest with the latest version? I assume there was some confusion about the temperature source, inside versus outside.

**Comment by richmitch** [comment]
Yes, that's working now.  I can see the inside temp

**Comment by cbrandlehner** [comment]
Closing as per feedback from @richmitch
